# Generated by Django 3.1.4 on 2020-12-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('account', models.TextField()),
                ('password', models.IntegerField(default=0)),
            ],
        ),
    ]
