# Generated by Django 3.1.4 on 2020-12-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('reader', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
